@extends('tentapress-admin::layouts.shell')

@section('title', 'Import')

@section('content')
    <div class="tp-page-header">
        <div>
            <h1 class="tp-page-title">Import</h1>
            <p class="tp-description">Import a bundle exported from another TentaPress installation.</p>
        </div>
    </div>

    <div class="tp-metabox">
        <div class="tp-metabox__title">Upload export zip</div>
        <div class="tp-metabox__body space-y-5">
            <form
                method="POST"
                action="{{ route('tp.import.analyze') }}"
                enctype="multipart/form-data"
                class="space-y-4">
                @csrf

                <div class="tp-field">
                    <label class="tp-label">Export zip</label>
                    <input type="file" name="bundle" class="tp-input" accept=".zip" required />
                    <div class="tp-help">Upload the zip generated by the Export plugin.</div>
                </div>

                <div class="flex gap-2">
                    <button type="submit" class="tp-button-primary">Analyze bundle</button>
                </div>

                <div class="tp-muted text-xs">We’ll show a summary before anything is imported.</div>
            </form>
        </div>
    </div>
@endsection
